#!/usr/bin/env bash
PYTHON=/usr/bin/python
ARGS=""
while getopts ":p:" opt; do
    case $opt in
        p)
            PYTHON=$OPTARG
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
        *)
            ARGS="$ARGS -$OPTARG"
    esac
done

$PYTHON test_check.py
if [[ $? != 0 ]]
then
    exit 1
fi

pass=0
for script in `find src -name \*.py`; do
    echo $script
    $PYTHON $script $ARGS
    if [[ $? != 0 ]]
    then
        pass=1
    fi
done
if [[ $pass == 0 ]]
then
    echo "ALL OK"
else
    echo "FAILURE"
fi
